#!/usr/bin/env python3
"""Managed linter checks — tier 1 of the enforcement split. Re-vendored into a fork by
`./bootstrap.sh --update`; **do not edit this file in a fork** — your edits are overwritten on
the next update. Fork-local checks go in `tools/lint.py` (the wrapper), which imports this
module and passes its own checks to `run(extra_checks=...)`.

ERROR blocks the commit; WARN advises. The ERROR/WARN assignment IS the split: a
check is ERROR only if a violation is unambiguously wrong; a loose mechanical shadow
of a semantic rule is always WARN (a high-precision backstop, never a substitute for
judgment). Each check's docstring names the governance rule it shadows — the linter
is indexed to the semantic layer, not a replacement for it.

**Public surface for sibling managed tools.** `backfill_decision_status.py` (co-vendored in
the same managed set, same version stamp) imports from this module: `is_decision_doc`,
`validate_superseded_target`, `strip_code`, `_frontmatter`, `_FM_RE`, `LINK_RE`, `md_files`,
`ROOT`, `DECISION_STATUSES`. Treat these as a contract — they ship and version together, so a
rename here must update the sibling in the same change (the underscore-prefixed two are a known
exception to "private," tracked on the debt shelf for a future de-underscore pass).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC_DIRS = ["docs"]  # directories holding governed markdown
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
FENCE_RE = re.compile(r"```.*?```", re.S)        # fenced code blocks
_CODE_SPAN_RE = re.compile(r"`[^`]+`")            # inline code spans


def strip_code(text):
    """Remove fenced code blocks and inline code spans so link/anchor checks don't fire on
    example syntax inside code (e.g. an illustrative `[x](<file>)` in a doc's own how-to).
    Kept behaviourally identical to `cms_lint._strip_code` — edit both together."""
    return _CODE_SPAN_RE.sub("", FENCE_RE.sub("", text))

errors = []
warnings = []


def error(path, msg):
    errors.append(f"ERROR  {os.path.relpath(path, ROOT)}: {msg}")


def warn(path, msg):
    warnings.append(f"WARN   {os.path.relpath(path, ROOT)}: {msg}")


def md_files():
    yield os.path.join(ROOT, "README.md")
    for d in DOC_DIRS:
        for dirpath, _, names in os.walk(os.path.join(ROOT, d)):
            for n in names:
                if n.endswith(".md"):
                    yield os.path.join(dirpath, n)


def check_relative_links(path, text):
    """Shadows: 'every pointer targets an existing file'. Mechanical → ERROR.
    Links inside code (fenced blocks OR inline spans) are illustrative (a README skeleton,
    or a forward-reference to a yet-to-be-generated artifact), not live pointers — skip them."""
    text = strip_code(text)
    for m in LINK_RE.finditer(text):
        target = m.group(1).split("#")[0]
        if not target or "://" in target or target.startswith("mailto:"):
            continue
        resolved = os.path.normpath(os.path.join(os.path.dirname(path), target))
        if not os.path.exists(resolved):
            error(path, f"broken relative link: {m.group(1)}")


def check_opening_thesis(path, text):
    """Shadows: 'open with a one-sentence thesis'. Loose backstop → always WARN."""
    body = re.sub(r"^---\n.*?\n---\n", "", text, flags=re.S)  # skip frontmatter
    lines = [l for l in body.splitlines() if l.strip() and not l.startswith("#")]
    if lines and len(lines[0]) > 400:
        warn(path, "opening line is very long — is it still a one-sentence thesis?")


DECISION_STATUSES = {"decided", "superseded"}
_FM_RE = re.compile(r"^---\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|$)", re.S)  # tolerate CRLF + a closing --- that ends the file
_FM_KEY_RE = re.compile(r"^([A-Za-z_][\w-]*):\s*(.*)$")


def _frontmatter(text):
    """Flat dict of top-level `key: value` pairs from a leading `---`…`---` block;
    {} if absent. Sufficient for `status:`/`superseded_by:` — not a full YAML parser."""
    m = _FM_RE.match(text)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        km = _FM_KEY_RE.match(line)
        if km:
            out[km.group(1)] = km.group(2).strip().strip("\"'")
    return out


def is_decision_doc(path):
    """A decision doc: a `*.md` (not README) whose immediate parent dir is `decisions/`
    anywhere under `docs/`. Depth-robust so module-internal `docs/<module>/decisions/`
    dirs are covered without re-anchoring. Single source of truth for *what the
    decision-status convention governs* — `check_decision_status` and the backfill helper
    (`backfill_decision_status.py`) both gate on this, so the discovery rule never forks."""
    parts = os.path.relpath(path, ROOT).split(os.sep)
    if os.path.basename(path) == "README.md" or len(parts) < 2:
        return False
    return "docs" in parts[:-1] and parts[-2] == "decisions"


def validate_superseded_target(path, target):
    """Pure check for the `superseded_by:` rule: returns an error *message* (str) if
    `target` is missing or doesn't resolve to an existing sibling of `path`, else None.
    No side effects — the single source of the resolve rule, shared by `check_decision_status`
    and the backfill helper so the helper can validate *before* writing (not after)."""
    if not target:
        return ("`status: superseded` requires `superseded_by:` (a reversal with no "
                "successor is itself a new decision doc — see docs/decisions/README.md)")
    resolved = os.path.normpath(os.path.join(os.path.dirname(path), target))
    if not os.path.exists(resolved):
        return f"`superseded_by: {target}` resolves to no file"
    return None


def check_decision_status(path, text):
    """Shadows: 'a decision doc declares live-vs-dead at the file, not only in the
    verdict registry' (docs/decisions/README.md). Every decision doc (see `is_decision_doc`)
    carries frontmatter `status:` in {decided, superseded}; a `superseded` doc needs a
    `superseded_by:` resolving to an existing sibling. Mechanical → ERROR. Self-gates:
    a repo with no `docs/**/decisions/` dir never trips it."""
    if not is_decision_doc(path):
        return
    fm = _frontmatter(text)
    status = fm.get("status")
    if status is None:
        error(path, "decision doc missing frontmatter `status:` (expected decided|superseded)")
        return
    if status not in DECISION_STATUSES:
        error(path, f"decision doc `status: {status}` not in {sorted(DECISION_STATUSES)}")
        return
    if status == "superseded":
        msg = validate_superseded_target(path, fm.get("superseded_by"))
        if msg:
            error(path, msg)


ARCH_DOCTYPE = "architecture"
_CODESPAN_RE = re.compile(r"`([^`]+)`")
# A reference token is word-chars / `.` / `-` / `/` / `§`, with up to two `:` separators
# (path, path:symbol, repo:path:symbol). This deliberately excludes spaces, parens, etc. so a
# prose code span like `.validate()` or `cms update` is NOT mistaken for a reference.
_REF_TOKEN_RE = re.compile(r"\A[\w.\-/§]+(?::[\w.\-/§]+){0,2}\Z")


def _looks_like_path(s):
    return "/" in s or "." in s  # a bare word (`Command`) is a symbol name, not a path ref


def _parse_arch_reference(token):
    """Parse one code-span token into (repo|None, path, symbol|None) per the three reference
    forms in method/architecture-doc.md, or None if the token isn't a reference at all."""
    if not _REF_TOKEN_RE.match(token):
        return None
    if token.startswith("/"):
        rest = token[1:]
        if "/" not in rest and "." not in rest:
            return None  # a `/slash-command` (single segment, no extension) — not a reference
        return (None, token, None)  # an absolute path → _resolve ERRORs (refs are repo-relative)
    parts = token.split(":")
    if len(parts) == 1:
        # A bare path ref must contain a '/'. A dotted-but-slashless token (`config.yaml`,
        # `v1.2`, `e.g.`, `.cms-version`) is prose, not a reference — a top-level file is
        # referenced with an anchor (`road.md:§2`) or under a dir, never bare. Kills the
        # false-positive surface that "contains a dot" would otherwise open.
        return (None, parts[0], None) if "/" in parts[0] else None
    if len(parts) == 2:
        if _looks_like_path(parts[0]):
            return (None, parts[0], parts[1])      # local  path:symbol
        if _looks_like_path(parts[1]):
            return (parts[0], parts[1], None)      # cross-repo  repo:path
        return None
    return (parts[0], parts[1], parts[2])          # cross-repo  repo:path:symbol


def _resolve_arch_reference(ref, token):
    """Return an error message if `ref` doesn't resolve against the live tree, else None.
    A cross-repo reference whose repo is not a reachable sibling **self-gates to silence**
    (returns None) — the check can't verify what it can't see."""
    repo, path, symbol = ref
    if repo:
        base = os.path.join(os.path.dirname(ROOT), repo)
        if not os.path.isdir(base):
            return None  # unreachable sibling repo → self-gate (no false miss)
    else:
        base = ROOT
    if os.path.isabs(path):
        return f"architecture reference `{token}` → must be repo-relative, not absolute"
    target = os.path.normpath(os.path.join(base, path.rstrip("/")))
    if target != base and not target.startswith(base + os.sep):
        return f"architecture reference `{token}` → escapes the repo root"
    if not os.path.exists(target):
        return f"architecture reference `{token}` → path does not resolve"
    if symbol:
        if os.path.isdir(target):
            return f"architecture reference `{token}` → symbol named on a directory"
        try:
            with open(target, encoding="utf-8") as f:
                if symbol not in f.read():
                    return f"architecture reference `{token}` → anchor `{symbol}` not found in {path}"
        except OSError:
            return f"architecture reference `{token}` → cannot read {path}"
    return None


def check_architecture_freshness(path, text):
    """Shadows the `FRESH` invariant (method/architecture-doc.md): a doc that opts into the
    architecture doctype (frontmatter `doctype: architecture`) must have every reference — the
    three code-span forms (path, path:symbol, repo:path:symbol) — resolve against the live tree.
    Mechanical → ERROR. Self-gates twice: a doc without the marker emits nothing; a cross-repo
    reference whose repo isn't a reachable sibling self-gates to silence. A *near-miss* doctype
    value (`architecure` typo) WARNs rather than silently opting the doc out — the value-based
    opt-in isn't typo-proof the way the decision-doc dir-based one is."""
    doctype = _frontmatter(text).get("doctype")
    if doctype != ARCH_DOCTYPE:
        if doctype and "arch" in doctype.lower():
            warn(path, f"frontmatter `doctype: {doctype}` is not the recognized `{ARCH_DOCTYPE}` "
                       "— typo? the architecture freshness check is being skipped for this doc")
        return
    for m in _CODESPAN_RE.finditer(FENCE_RE.sub("", text)):  # fenced examples aren't live refs
        ref = _parse_arch_reference(m.group(1).strip())
        if ref is None:
            continue
        msg = _resolve_arch_reference(ref, m.group(1).strip())
        if msg:
            error(path, msg)


def check_stamp_drift():
    """Shadows: 'a fork's managed checks track CMS canonical' (WS2 propagation). Advisory →
    WARN. **No hashing here** — bash is the sole hash producer: it stamps the fork's
    `tools/.cms-version` at vendor time and writes a committed canonical `tools/.cms-manifest`
    in the CMS clone; this check just string-compares the two. Self-gates to silence (never a
    false alarm) when there's no local stamp (CMS itself, or an unmigrated legacy fork) or no
    reachable canonical (`CMS_SRC` unset, or its manifest missing — a disconnected fork: honest
    dormancy, no-worse-than-today). Repo-level: runs once, not per file."""
    stamp_file = os.path.join(ROOT, "tools", ".cms-version")
    if not os.path.exists(stamp_file):
        return
    src = os.environ.get("CMS_SRC")
    if not src:
        return
    manifest = os.path.join(src, "tools", ".cms-manifest")
    if not os.path.exists(manifest):
        return
    with open(stamp_file, encoding="utf-8") as f:
        local = f.read().strip()
    with open(manifest, encoding="utf-8") as f:
        canonical = f.read().strip()
    if local != canonical:
        warn(stamp_file, "managed checks differ from CMS canonical — run "
                         "`./bootstrap.sh --update <this repo>` from the CMS clone to refresh")


# The managed check set. Fork-local checks are NOT added here — they live in the
# tools/lint.py wrapper and reach run() via extra_checks.
SHARED_CHECKS = [check_relative_links, check_opening_thesis, check_decision_status,
                 check_architecture_freshness]
# Repo-level managed checks: run once over the repo, not per markdown file.
REPO_CHECKS = [check_stamp_drift]


def run(extra_checks=()):
    """Run the managed checks plus any fork-local `extra_checks` over the governed corpus.
    Returns a process exit code (1 if any ERROR, else 0)."""
    checks = list(SHARED_CHECKS) + list(extra_checks)
    for path in md_files():
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as f:
            text = f.read()
        for check in checks:
            check(path, text)

    for repo_check in REPO_CHECKS:
        repo_check()

    for w in warnings:
        print(w)
    for e in errors:
        print(e)
    if errors:
        print(f"\n{len(errors)} error(s) — commit blocked. (Warnings are advisory.)")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(run())
